import type { Metadata } from "next";
import "./globals.css";
import Header from "./_component/Header";
import Footer from "./_component/Footer";

export const metadata: Metadata = {
  title: "何回も作るよ",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ja">
      <body>
        <Header/>
        {children}
        <Footer/>
      </body>
    </html>
  );
}
